/**
 * @description Module that gets and adds the price
 * for each trip (i.e. row of a csv file generated by
 * STS luxury).
 *
 * @author Bryan Guillen
 */

 /**********************
  * TODOs
  * - Remove '""' from updated CSV
  * - Wrap this logic into an express app
  *   - When deploying ensure googleApiKey is private
  * - Create a frontend to interact with this
  *   express app
  ***********************/

/**********************
 * Variables
 ***********************/

const addPricesToCsv = require('./reportPrices/addPricesToCsv');
const csvFile = './stsTripData.csv';

/**********************
 * Exec
 ***********************/

addPricesToCsv(csvFile);
